### PR TITLE
Upgrade shaven dependency

### LINKED ISSUE #232: old dependency version prevent install with engine-strict=true
Can you upgrade shaven to `2.0.0`?
`0.8.1` contains `node: ~0.12.0` in `engines`.
It works on new nodejs versions, but can't be installed with `engine-strict=true`.

### PR DESCRIPTION
**Pull request by vbjay**
Closes #232 
Related 
#209 
ad-si/shaven#44

### CODE REVIEW

**Comment by vbjay** [comment]
image

Your builds are still failing 4 years and counting.

**Comment by imsky** [comment]
thanks @vbjay 

i'm reworking the builds sometime soon - likely migrating off of travis

**Comment by ryanrapini** [comment]
I'm still getting this error, am I missing something? I think you have to publish to npm for this update to go in.

**Comment by vbjay** [comment]
Correct.  Npm hasn't been updated.

**Comment by imsky** [comment]
release coming out next week

**Comment by imsky** [comment]
@vbjay @ryanrapini 2.9.8 just released, give that a try

**Comment by imsky** [comment]
@vbjay @ryanrapini 2.9.9 - just released - should fix the issue

**Comment by ryanrapini** [comment]
Thanks, fixed the issue for me.

**Pull request merged**
